### ISSUE TITLE
keyserver response handling

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#375]
```
TypeError: Cannot read property 'toLowerCase' of undefined
    at db_create_search_index_list (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/storage.js:294:16)
    at db_contact_object (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/storage.js:321:17)
    at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/gmail_elements/shared/compose.js:309:30
    at Object.success (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/keyserver.js:54:7)
    at i (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:27151)
    at Object.fireWith [as resolveWith] (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:27914)
    at z (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:4:12120)
    at XMLHttpRequest.<anonymous> (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:4:15680)
```

**Comment by tomholub** [comment]
error from old version
